belledeluxe2_codigo/belleluxe/api/urls.py
from django.urls import path, include
from api import views
from rest_framework import routers
app_name = 'api'

router = routers.DefaultRouter()
router.register(r'campaign', views.CrudCampaign)
router.register(r'category', views.CrudCategory)
router.register(r'customer', views.CrudCustomer)
router.register(r'productos', views.CrudProductos)
router.register(r'itemPedido', views.CrudItemPedido)
router.register(r'pedido', views.CrudPedido)



urlpatterns=[
    #cruds
    path('cruds/', include(router.urls)),
    #tienda 
    path('tienda/productos/', views.ListaProductos.as_view(), name="api_tienda_producto"),
    #Cuenta
    path('registro/', views.RegistroAPI.as_view(), name="api_login"),
    path('csrf_cooky/', views.getcsrftoken.as_view(), name="api_token"),
    path('autenticacion/', views.CheckAuthenticatedView.as_view(), name="autenticacion" ),
    path('iniciar_sesion/', views.LoginView.as_view(), name="api_loginn"),
    path('cerrar_sesion/', views.LogoutView.as_view(), name="api_logout"),
    #Usuarios
    path('eliminar_usuario/', views.DeleteAccountView.as_view(), name = "deleteUser"),
    path('ver_usuarios/', views.GetUsersView.as_view(), name = "getUsers"),
    path('ver_usuario/', views.GetCustomerView.as_view(), name = "GetCus"),
    path('actualizar_user/', views.UpdateCustomerProfileView.as_view(), name = "UpdateUser"),
    #Pedidos
    path('ver_pedido/', views.verpedidoAPI.as_view(), name = "apiVerPedido"),
    path('crearpedido/', views.pedidoAPI.as_view(), name = "apiPedido"),

    


    
    ] 

belledeluxe2_codigo/belleluxe/belleluxe/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('adm/', include("core.urls")),
    path('accounts/', include('django.contrib.auth.urls')),
    path('tienda/', include ("tienda.urls")),
    path('carrito/', include ("carrito.urls")),
    path('api/', include ("api.urls")),
    path('api-auth/', include('rest_framework.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

belledeluxe2_codigo/belleluxe/carrito/urls.py
from django.urls import path

from . import views

app_name = 'carrito'
 
urlpatterns = [
    path('', views.corder, name="order"),
    path('add/',views.carrito_add, name ="carrito_add"),
    # path('detail/carrito/<int:pk>/', views.DetailCarrito, name='detail_carrito'),
    path('update/', views.UpdateCarrito, name='update_carrito'),
    path('delete/', views.DeleteCarrito, name='delete_carrito'),
    path('pago/', views.pagoos.as_view(), name='pagoC'),
    path('pedidos/', views.verPedidos.as_view(), name='pedidos'),


]

belledeluxe2_codigo/belleluxe/core/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views


app_name="core"
urlpatterns=[
    path('', views.adm.as_view(), name="adm"),

    path('camping/', views.Campaign.as_view(), name="campaign"),
    path('detail/camping/<int:pk>/', views.DetailCampaign.as_view(), name='detail_campaign'),
    path('update/camping/<int:pk>/', views.UpdateCampaign.as_view(), name='update_campaign'),
    path('delete/camping/<int:pk>/', views.DeleteCampaign.as_view(), name='delete_campaign'),
    path('new/camping/', views.NewCampaign.as_view(), name='Newcampaign'),

    path('list/category/', views.list_category.as_view(), name="category"),
    path('detail/category/<int:pk>/', views.DetailCategory.as_view(), name='detail_category'),
    path('update/category/<int:pk>/', views.UpdateCategory.as_view(), name='update_category'),
    path('delete/category/<int:pk>/', views.DeleteCategory.as_view(), name='delete_category'),
    path('new/category/', views.NewCategory.as_view(), name='Newcategory'),

    path('product/', views.product.as_view(), name="product"),
    path('recover/product/<int:pk>/', views.RecoverProduct.as_view(), name='recover_product'),
    path('update/product/<int:pk>/', views.UpdateProduct.as_view(), name='update_product'),
    path('delete/product/<int:pk>/', views.DeleteProduct.as_view(), name='delete_product'),
    path('new/product/', views.NewProduct.as_view(), name='new_product'),

    path('list/customer/', views.list_customer.as_view(), name="customer"),
    path('detail/customer/<int:pk>/', views.DetailCustomer.as_view(), name='detail_customer'),
    path('update/customer/<int:pk>/', views.UpdateCustomer.as_view(), name='update_customer'),
    path('delete/customer/<int:pk>/', views.DeleteCustomer.as_view(), name='delete_customer'),

    path('list/ItemPedido', views.list_ItemPedido.as_view(), name="Itempedido"),
    path('recover/ItemPedido/<int:pk>/', views.RecoverItemPedido.as_view(), name='recover_itempedido'),
    path('update/ItemPedido/<int:pk>/', views.UpdateItemPedido.as_view(), name='update_itempedido'),
    path('delete/ItemPedido/<int:pk>/', views.DeteleItemPedido.as_view(), name='delete_itempedido'),  
   
    path('list/Pedido', views.list_pedidos.as_view(), name="pedido"),
    path('detail/Pedido/<int:pk>/', views.Detailpedidos.as_view(), name='detail_pedido'),
    path('update/Pedido/<int:pk>/', views.Updatepedidos.as_view(), name='update_pedido'),
    path('delete/Pedido/<int:pk>/', views.Deletepedidos.as_view(), name='delete_pedido'),   
    
]

belledeluxe2_codigo/belleluxe/home/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views


app_name="home"
urlpatterns=[
    path('', views.inicio.as_view(), name="inicio"),
    path('nosotros/', views.nosotros.as_view(), name="nosotros"),
    path('blog/', views.blog.as_view(), name="blog"),
    path('servicios/', views.servicios.as_view(), name="servicios"),
    path('politicas/', views.politicas.as_view(), name="politicas"),
    path('perfil/<int:pk>/', views.perfil.as_view(), name="perfil"),

# Accesos
    path('registro/', views.registrar.as_view(), name='registro'),
    path('acceso/', views.Acceso.as_view(), name='acceso'),
    path('cierre/',views.cierre, name='cierre'),
    path('perfil/actualiar/<int:pk>/', views.UpdateProfile.as_view(), name="actualizarPerfil"),

]

belledeluxe2_codigo/belleluxe/tienda/urls.py
from django.contrib import admin
from django.urls import path
from tienda import views


#  Compras 
app_name= "tienda"
urlpatterns=[
    path('', views.tienda.as_view(), name="tienda"),
    path('hombre/', views.hombre.as_view(), name="hombre"),
    path('mujer/', views.mujer.as_view(), name="mujer"),
    path('producto/<int:pk>/', views.producto.as_view(), name='producto'),
    path('categoria/<int:pk>/', views.Pcategoria.as_view(), name='Pcategoria'),
    path('busqueda/', views.busqueda.as_view(), name='busqueda'),
]

belledeluxe2_codigo/belleluxe/templates/base/admin.html
<html>
    <head>
        <meta charset="utf-8">

        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        <style>
            .sidebar {
              margin: 0;
              padding: 0;
              width: 170px;
              background-color: #ccd1cb;
              position: fixed;
              height: 100%;
              overflow: auto;
            }
            .sidebar a {
              display: block;
              color: black;
              padding: 16px;
              text-decoration: none;
            }
            
            .sidebar a.active {
              background-color: #748e81;
              color: white;
            }
            .sidebar a:hover:not(.active) {
              background-color: #555;
              color: #ccd1cb;
            }
            div.content {
              margin-left: 200px;
              padding: 1px 16px;
              height: 1000px;
            }
            @media screen and (max-width: 700px) {
              .sidebar {
                width: 100%;
                height: auto;
                position: relative;
              }
              .sidebar a {float: left;}
              div.content {margin-left: 0;}
            }
            @media screen and (max-width: 400px) {
              .sidebar a {
                text-align: center;
                float: none;
              }
            } 
            body{
            background-color : #e9ede8
            }
        </style>
        
    </head> 
    <body>
        <!-- The sidebar -->
<div class="sidebar">
    <a class="active">BELLE D' LUXE Admin</a>
    <a href="{% url 'core:product'%}">Productos</a>
    <a href="{% url 'core:category' %}">Categorias</a>
    <a href="{% url 'core:campaign' %}">Campañas</a>    
    <a href="{% url 'core:customer' %}">Clientes</a>
    <a href="{% url 'core:pedido' %}">Pedidos</a>
    <a href="{% url 'core:Itempedido' %}">Subpedidos</a>
    <a href="{% url 'home:inicio' %}">Salir</a>
  </div>
  
  <!-- Page content -->
  <div class="content">
    {% block content %}
    {% endblock content %}
  </div> 
                    
           
    </body>
</html>

belledeluxe2_codigo/belleluxe/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>{% block title %}BelleD'Luxe{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>

</head>
<body>
    <style>
        #navegador{
                list-style-type: none;
                border: 1px solid rgb(20, 20, 20);
        }
    </style>

    <!-- barra de navegacion  -->
    <nav id="navegador" class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a href="{% url 'home:inicio' %}" class = navbar-brand> <img src="{% static 'imagenes/logonegro.png' %}" alt="" weight="80px" height="40px"></a>    
            
            
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>          



            <!-- inicio de opciones de categoría -->
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <li class="nav-item">
                </li>
                
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if category %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Categorías</a>
                            <figcaption class="blockquote-footer">
                                Tienda
                            </figcaption>
                            <ul class="dropdown-menu">
                                <li><a class = "dropdown-item" href = "{% url 'tienda:tienda' %}"> Ver todo </a></li>
                                {% for category in category %}
                                    <li>
                                        <a class="dropdown-item" href="{% url 'tienda:Pcategoria' category.id %}">{{ category.name }}</a>          
                                    </li>
                                {% endfor %}
                            </ul>
                        </li>
                    {% else %}
                        <p>No hay categorías disponibles.</p>
                    {% endif %}
                </ul>
            </div>
            <!-- Fin de opciones de categoría -->

            

        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent" >
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">    
                
                <li class="nav-item dropdown">

                    
                    <!-- inicio de opciones de perfil -->
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-person" style="font-size: 150%; color: black;"></i></a>
                    <ul class="dropdown-menu">
                        {% if request.user.is_authenticated %}
                            <li><a class="dropdown-item" href="{% url 'carrito:pedidos' %}">Pedidos</a></li>

                            {% if request.user.is_staff %}
                            <li><a class="dropdown-item" href="{% url 'core:adm' %}">Admin</a></li>
                            {% else %}
                            <li><a class="dropdown-item" href="{% url 'home:perfil' request.user.pk %}">Perfil</a></li>
                          

                            {% endif %}
                            <li><hr class="dropdown-divider"></li> 
                            <li><a class="dropdown-item" href="{% url 'home:cierre' %}">Cerrar sesión</a></li>
                        {% else %}
                            <li><a class="dropdown-item" href="{% url 'home:acceso' %}">Iniciar sesión</a></li>
                            <li><a class="dropdown-item" href="{% url 'home:registro' %}">Crear una cuenta</a></li>
                        {% endif %}
                    </ul>
                    <!-- Fin de opciones de perfil-->


                    <!-- insertar espacio  -->
                    <li style="padding-right: 2rem">
                    </li>


                    <!-- INICIO ICONO DEL CARRITOOOO -->
                    <li class="nav-item" style="padding-right: 3rem" >
                        <a class="nav-link active" aria-current="page" href="{% url 'carrito:order' %}">  
                        
                        {% with total_qty=carrito|length %}
                            <div id="carrito-qty" class="d-inline-flex">
                                {% if total_qty > 0 %}
                                    {{ total_qty }}
                                {% else %}
                                    0
                                {% endif %}
                            </div>
                        {% endwith %} 

                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                            class="bi bi-cart3" viewBox="0 0 16 16">
                            <path
                                d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
                        </svg>
                        </a>
                    </li>
                    <!-- FIN ICONO DEL CARRITOO -->



                    <!-- inicio de opciones de busqueda -->
                    <!-- <form class="container-fluid" method="GET" action="{% url 'tienda:busqueda' %}">    
                        <div class="input-group">
                          <input type="text" class="form-control" placeholder="" aria-label="Buscar" aria-describedby="basic-addon1" name="b">
                          <span class="input-group-text" id="basic-addon1"> 
                                <button class="btn btn-default my-2 my-sm-0" type = "button">
                                    <i class="bi bi-search"></i>
                                </button> 
                            </span>
                        </div>
                    </form>   -->
                    <!-- fin de opciones de busqueda -->
         
                </li>  

            </ul> 
        </div>

    </nav>


{% block content %} {% endblock content %}
      
      <!-- Grid container -->
    
      <!-- Copyright -->
      <div class="text-center" style="background-color: rgba(0, 0, 0, 0);">
        <ul class="list-inline">
            <br>
            <br>
            <br>
            <br>


            <div class="text-center">
                <ul>
                    <a class="text-black" href="{% url 'home:nosotros' %}">Sobre BELLE D' LUXE </a>
                    <li class="list-inline-item"></li>
                    <li class="list-inline-item"></li>
                    <a class="text-black" href="{% url 'home:blog' %}">Nuestro Blog</a>
                    <li class="list-inline-item"></li>
                    <li class="list-inline-item"></li>
                    <a class="text-black" href="{% url 'home:servicios' %}">Servicios</a>
    
                  </ul>              
            </div>
    
    
    


  <!-- Section: Social media -->
  <section class="mb-4">
    <!-- Facebook -->
    <a
      class="btn btn-link btn-floating btn-lg text-dark m-1"
      href="https://www.facebook.com/belleedeluxe"
      role="button"
      data-mdb-ripple-color="dark"
      ><i class="bi bi-facebook" style="font-size: 100%; color: rgb(0, 0, 0);" ></i></a>

    <!-- Google -->
    <a
      class="btn btn-link btn-floating btn-lg text-dark m-1"
      href="https://www.google.com/search?q=belle+de+luxe+tijuana&sca_esv=573670241&biw=1920&bih=937&tbm=lcl&ei=tY0sZb_JKd_UkPIP4OuFqAM&ved=0ahUKEwj_98WqsfmBAxVfKkQIHeB1ATUQ4dUDCAk&uact=5&oq=belle+de+luxe+tijuana&gs_lp=Eg1nd3Mtd2l6LWxvY2FsIhViZWxsZSBkZSBsdXhlIHRpanVhbmEyChAhGKABGMMEGApI_hBQkw1Ykw1wAHgAkAEAmAGTAaAB2gKqAQMxLjK4AQPIAQD4AQHCAgUQABiiBMICCBAAGIkFGKIEiAYB&sclient=gws-wiz-local#rlfi=hd:;si:;mv:[[32.52364412063617,-116.93859226079246],[32.49498109755391,-117.00296527714988]]"
      role="button"
      data-mdb-ripple-color="dark"
      ><i class="bi bi-google" style="font-size: 100%; color: rgb(0, 0, 0);"></i
    ></a>

    <!-- Instagram -->
    <a
      class="btn btn-link btn-floating btn-lg text-dark m-1"
      href="https://www.instagram.com/belleedeluxe/"
      role="button"
      data-mdb-ripple-color="dark"
      ><i class="bi bi-instagram" style="font-size: 100%; color: black;" ></i></a>


      <!-- Tiktok -->
      <a
      class="btn btn-link btn-floating btn-lg text-dark m-1"
      href="https://www.tiktok.com/@belleedeluxe"
      role="button"
      data-mdb-ripple-color="dark"
      ><i class="bi bi-tiktok" style="font-size: 100%; color: black;" ></i></a>
  </section>
  <!-- Section: Social media -->

            <br>
            <li class="list-inline-item">            @belledeluxe Baja California Norte, México             </li>
            <li class="list-inline-item"></li>
            <a class="text-black" href="{% url 'home:politicas' %}">Politica de privacidad y cookies | condiciones de venta</a>
            <br>
          </ul>              
      </div>
      <!-- Copyright -->
    


      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>    
</body>
</html>

belledeluxe2_codigo/belleluxe/templates/base/basetienda.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    
</head>
<body>
    <style>

        #navegador{
        
                    list-style-type: none;
                    border: 1px solid rgb(20, 20, 20);
         
        }
        </style>

    <!-- barra de navegacion  -->
    <nav id="navegador" class="navbar navbar-expand-lg">
        <div class="container-fluid">
            <a href="{% url 'home:inicio' %}" class = navbar-brand> <img src="{% static 'imagenes/logonegro.png' %}" alt="" weight="80px" height="40px"></a>    
            
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>          

            <div class="collapse navbar-collapse" id="navbarSupportedContent" >
                <ul class="navbar-nav me-auto mb-2 mb-lg-0" >
                    <li class="nav-item" ><a class="nav-link active" aria-current="page" href="{% url 'tienda:tienda' %}">TIENDA</a></li>
                </ul>                
            </div>
           <form class="form-inline my-2 my-lg-0 custom-form d-flex" style="border: none;">
              <!-- Utiliza la clase "flex-grow-1" para hacer que el campo de búsqueda ocupe el espacio disponible -->
              <input class="form-control mr-sm-2 flex-grow-5" type="search" placeholder="Search" aria-label="Search">
              <!-- Aplica la clase "transparent-button" al botón para hacerlo transparente -->
              <button class="btn btn-outline-success transparent-button" style="color: rgb(9, 9, 9);" type="submit">Buscar</button>
          </form> 
        </div>
        <div class="collapse navbar-collapse" id="navbarSupportedContent" style="padding-right: 30px;">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                              
             
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-person" style="font-size: 150%; color: black;"></i></a>
                    <ul class="dropdown-menu">
                        {% if request.user.is_authenticated %}
                            <li><a class="dropdown-item" href="{% url 'home:perfil' request.user.pk %}">Perfil</a></li>
                            <li><a class="dropdown-item" href="{% url 'carrito:pedidos' %}">Pedidos</a></li>
                            {% if request.user.is_staff %}
                            <li><a class="dropdown-item" href="{% url 'core:adm' %}">Admin</a></li>
                            {% endif %}
                            <li><hr class="dropdown-divider"></li> 
                            <li><a class="dropdown-item" href="{% url 'home:cierre' %}">Cerrar sesión</a></li>
                        {% else %}
                            <li><a class="dropdown-item" href="{% url 'home:acceso' %}">Iniciar sesión</a></li>
                            <li><a class="dropdown-item" href="{% url 'home:registro' %}">Crear una cuenta</a></li>
                        {% endif %}
                    </ul>
                    <li class="nav-item" ><a class="nav-link active" aria-current="page" href="{% url 'tienda:carrito' %}">  <i class="bi bi-cart" style="font-size: 150%; color: black;"></i></a></li>
                </li>  
            <!--  -->
            </ul> 
        </div>

    </nav>


      {% block content %}

      {% endblock content %}
      
      <!-- Grid container -->
    
      <!-- Copyright -->
      <div class="text-center" style="background-color: rgba(0, 0, 0, 0);">
        <ul class="list-inline">
            <br>
            <br>
            <br>
            <br>


            <div class="text-center">
                <ul>
                    <a class="text-black" href="{% url 'home:nosotros' %}">Sobre BELLE D' LUXE </a>
                    <li class="list-inline-item"></li>
                    <li class="list-inline-item"></li>
                    <a class="text-black" href="{% url 'home:blog' %}">Nuestro Blog</a>
                    <li class="list-inline-item"></li>
                    <li class="list-inline-item"></li>
                    <a class="text-black" href="{% url 'home:servicios' %}">Servicios</a>
    
                  </ul>              
            </div>
    
    
    


  <!-- Section: Social media -->
  <section class="mb-4">
    <!-- Facebook -->
    <a
      class="btn btn-link btn-floating btn-lg text-dark m-1"
      href="https://www.facebook.com/belleedeluxe"
      role="button"
      data-mdb-ripple-color="dark"
      ><i class="bi bi-facebook" style="font-size: 100%; color: rgb(0, 0, 0);" ></i></a>

    <!-- Google -->
    <a
      class="btn btn-link btn-floating btn-lg text-dark m-1"
      href="https://www.google.com/search?q=belle+de+luxe+tijuana&sca_esv=573670241&biw=1920&bih=937&tbm=lcl&ei=tY0sZb_JKd_UkPIP4OuFqAM&ved=0ahUKEwj_98WqsfmBAxVfKkQIHeB1ATUQ4dUDCAk&uact=5&oq=belle+de+luxe+tijuana&gs_lp=Eg1nd3Mtd2l6LWxvY2FsIhViZWxsZSBkZSBsdXhlIHRpanVhbmEyChAhGKABGMMEGApI_hBQkw1Ykw1wAHgAkAEAmAGTAaAB2gKqAQMxLjK4AQPIAQD4AQHCAgUQABiiBMICCBAAGIkFGKIEiAYB&sclient=gws-wiz-local#rlfi=hd:;si:;mv:[[32.52364412063617,-116.93859226079246],[32.49498109755391,-117.00296527714988]]"
      role="button"
      data-mdb-ripple-color="dark"
      ><i class="bi bi-google" style="font-size: 100%; color: rgb(0, 0, 0);"></i
    ></a>

    <!-- Instagram -->
    <a
      class="btn btn-link btn-floating btn-lg text-dark m-1"
      href="https://www.instagram.com/belleedeluxe/"
      role="button"
      data-mdb-ripple-color="dark"
      ><i class="bi bi-instagram" style="font-size: 100%; color: black;" ></i></a>


      <!-- Tiktok -->
      <a
      class="btn btn-link btn-floating btn-lg text-dark m-1"
      href="https://www.tiktok.com/@belleedeluxe"
      role="button"
      data-mdb-ripple-color="dark"
      ><i class="bi bi-tiktok" style="font-size: 100%; color: black;" ></i></a>
  </section>
  <!-- Section: Social media -->

            <br>
            <li class="list-inline-item">            @belledeluxe Baja California Norte, México.            </li>
            <li class="list-inline-item"></li>
            <a class="text-black" href="{% url 'home:politicas' %}">Politica de privacidad y cookies | condiciones de venta</a>
            <br>
          </ul>              
      </div>
      <!-- Copyright -->
    


      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>    
</body>
</html>